<?php
declare(strict_types=1);
$template = <<<'HTML'
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4f8ef"><title>Consulta de votos · Território PE</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><style>
:root{--ink:#123b2b;--muted:#687b6e;--green:#087a3e;--line:#dce8dc;--bg:#f4f8ef}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:'DM Sans',sans-serif}.top{height:70px;background:white;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 5vw}.brand{font:800 17px Manrope;color:var(--ink);text-decoration:none}.back{color:var(--green);font-weight:700;text-decoration:none;font-size:13px}.shell{max-width:1060px;margin:auto;padding:55px 5vw}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.15em;font-weight:700;color:var(--green)}h1{font:800 clamp(28px,4vw,42px) Manrope;margin:9px 0}.intro{color:var(--muted);margin:0 0 28px}.card{background:white;border:1px solid var(--line);border-radius:16px;padding:24px;box-shadow:0 8px 26px #17392d0b}.filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) 130px;gap:13px;align-items:end}label{display:block;font-size:12px;font-weight:700;margin-bottom:7px}select,button{height:44px;width:100%;border:1px solid #d8e2d9;border-radius:9px;background:white;padding:0 12px;font:inherit;color:var(--ink)}select:disabled{background:#f3f5f3;color:#89958c}button{border:0;background:var(--green);color:#fff;font-weight:700}button:disabled{opacity:.55}.status{font-size:12px;color:var(--muted);min-height:20px;margin:16px 0 0}.result{margin-top:22px}.summary{display:flex;align-items:center;justify-content:space-between;padding:17px 19px;background:#edf5ce;border-radius:11px;margin-bottom:14px}.summary span{font-size:12px;color:#47604f;font-family:Manrope,sans-serif;font-weight:800}.summary strong{font:800 24px Manrope;color:#155d36}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:13px 16px;border-bottom:1px solid #edf1ed}th{font-size:11px;color:var(--muted);background:#f8faf7}td{font-size:13px}td:last-child,th:last-child{text-align:right;font-variant-numeric:tabular-nums}tbody tr:last-child td{border-bottom:0}.empty{padding:24px;text-align:center;color:var(--muted);font-size:13px}.source{margin-top:17px;font-size:11px;color:#849187}@media(max-width:760px){.shell{padding:35px 4vw}.filters{grid-template-columns:1fr 1fr}.card{padding:17px}}@media(max-width:480px){.filters{grid-template-columns:1fr}.top{padding:0 4vw}}
</style></head><body><header class="top"><a class="brand" href="index.php">Território PE</a><a class="back" href="index.php">Voltar ao mapa</a></header><main class="shell"><div class="eyebrow">Pernambuco · Eleições 2026</div><h1>Consulta de votos por candidato</h1><p class="intro">Compare a votação de um candidato em todos os municípios pernambucanos.</p><section class="card"><form id="form" class="filters"><div><label for="office">Cargo</label><select id="office" required><option value="">Selecione o cargo</option><option value="estadual">Deputado estadual</option><option value="federal">Deputado federal</option><option value="senador">Senador</option><option value="governador">Governador</option><option value="presidente">Presidente</option></select></div><div><label for="party">Partido</label><select id="party" required disabled><option value="">Selecione o cargo primeiro</option></select></div><div><label for="candidate">Candidato</label><select id="candidate" required disabled><option value="">Selecione partido e cargo</option></select></div><button id="search" type="submit" disabled>Buscar</button></form><p id="status" class="status" role="status"></p><section id="result" class="result" hidden></section><div class="source">Fonte: Tribunal Superior Eleitoral (TSE) · resultados oficiais por município · 1º turno de 2026</div></section></main><script>
const office=document.getElementById('office'),party=document.getElementById('party'),candidate=document.getElementById('candidate'),search=document.getElementById('search'),status=document.getElementById('status'),result=document.getElementById('result');let sequence=0;
async function loadOptions(){const current=++sequence;party.disabled=true;candidate.disabled=true;search.disabled=true;result.hidden=true;party.innerHTML='<option value="">Carregando partidos…</option>';candidate.innerHTML='<option value="">Selecione um partido</option>';status.textContent='Carregando partidos e candidatos registrados em Pernambuco…';try{const data=await request({consulta:'partidos',cargo:office.value});if(current!==sequence)return;party.innerHTML='<option value="">Selecione o partido</option>'+data.parties.map(x=>'<option>'+escapeHtml(x)+'</option>').join('');party.disabled=false;status.textContent='';}catch(e){if(current===sequence)status.textContent=e.message}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function request(params){const url=new URL('dados_mapa.php',location.href);for(const [k,v]of Object.entries(params))url.searchParams.set(k,v);const response=await fetch(url,{headers:{Accept:'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível carregar os dados.');return data}
office.addEventListener('change',loadOptions);party.addEventListener('change',async()=>{const current=++sequence;candidate.disabled=true;search.disabled=true;result.hidden=true;if(!party.value)return;candidate.innerHTML='<option value="">Carregando candidatos…</option>';status.textContent='';try{const data=await request({consulta:'candidatos',cargo:office.value,partido:party.value});if(current!==sequence)return;candidate.innerHTML='<option value="">Selecione o candidato</option>'+data.candidates.map(c=>'<option value="'+escapeHtml(c.id)+'">'+escapeHtml(c.name)+(c.number?' · '+escapeHtml(c.number):'')+'</option>').join('');candidate.disabled=false;if(!data.candidates.length)status.textContent='Nenhum candidato encontrado para este partido e cargo.'}catch(e){if(current===sequence)status.textContent=e.message}});candidate.addEventListener('change',()=>{search.disabled=!candidate.value});document.getElementById('form').addEventListener('submit',async e=>{e.preventDefault();if(!office.value||!party.value||!candidate.value)return;search.disabled=true;result.hidden=true;status.textContent='Consultando os votos nas cidades de Pernambuco…';try{const data=await request({consulta:'buscar',cargo:office.value,partido:party.value,candidato:candidate.value});const rows=Object.entries(data.cities);result.innerHTML='<div class="summary"><span>Total de votos · '+escapeHtml(data.candidate)+'</span><strong>'+Number(data.total).toLocaleString('pt-BR')+'</strong></div>'+(rows.length?'<div class="table-wrap"><table><thead><tr><th>Município</th><th>Votos</th></tr></thead><tbody>'+rows.map(([city,votes])=>'<tr><td>'+escapeHtml(city)+'</td><td>'+Number(votes).toLocaleString('pt-BR')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Nenhum voto encontrado para este candidato.</div>');result.hidden=false;status.textContent='';}catch(err){status.textContent=err.message}finally{search.disabled=!candidate.value}});
</script></body></html>
HTML;
header('Content-Type: text/html; charset=UTF-8');
echo $template;
